### ISSUE TITLE
getAutoloadRealFile() strikes again

### ISSUE THREAD

**Issue by xrstf** [composer-php52/composer-php52#1]
Reported by [Rarst on Bitbucket](https://bitbucket.org/xrstf/composer-php52/issues/9/getautoloadrealfile-strikes-again)

> The usual...
> 
> composer self-update Updating to version de7123097e2e8a82997f41a844bee297dafcd4f0.
> [ErrorException] 
> Declaration of xrstf\Composer52\AutoloadGenerator::getAutoloadRealFile() sh
> ould be compatible with Composer\Autoload\AutoloadGenerator::getAutoloadRea
> lFile($useClassMap, $useIncludePath, $targetDirLoader, $useIncludeFiles, $v
> endorPathCode, $appBaseDirCode, $suffix, $useGlobalIncludePath, $prependAut
> oloader, $staticPhpVersion = 70000)

**Comment by garex** [comment]
Seems like it's fixed. At least at my case.
