### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by Diinisalma** [composer-php52/composer-php52#2]
I use plugin in my website, it seems the plugin using this composer. Once I loaded it, it failed. The message can see below, how could I fix this? 
Thank you for your help.
![image](https://user-images.githubusercontent.com/20138336/39472346-f2aaea00-4d72-11e8-995a-477fc3a2e8a3.png)

**Comment by garex** [comment]
@Diinisalma pls provide more appropriate bug report.

Currently there is zero info about your issue.

**Comment by Diinisalma** [comment]
I have checked web console and there's no error message.

**Comment by garex** [comment]
@Diinisalma check php error log.

**Comment by Diinisalma** [comment]
I know why is it. In the plugin there is file and it seems they mistaken to put the enclosed tag, so that's why it produces error. 
Thank you for your responding.
I'm sorry for bothering you.
